# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
