# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatoApp', '0003_make_email_unique_20170304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.CharField(choices=[('HI', 'High school'), ('UG', 'Undergraduate student'), ('BC', 'Bachelor'), ('GD', 'Graduate student'), ('MA', 'Master'), ('PD', 'PHD student'), ('DC', 'Doctor')], default='UG', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='zipcode',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
