# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatoApp', '0006_email_field_20170305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
