# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatoApp', '0007_unique_skill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='jobneedskill',
            unique_together=set([('job', 'skill')]),
        ),
        migrations.AlterUniqueTogether(
            name='userhasskill',
            unique_together=set([('user', 'skill')]),
        ),
    ]
